DROP TABLE IF EXISTS `customers`;

CREATE TABLE IF NOT EXISTS customers (
id INT NOT NULL AUTO_INCREMENT,
firstName VARCHAR(25) NOT NULL,
surname VARCHAR(35) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS `items`;

CREATE TABLE IF NOT EXISTS items (
id INT NOT NULL AUTO_INCREMENT,
productName VARCHAR(50) NOT NULL,
price FLOAT(6,2) NOT NULL,
PRIMARY KEY (id)
);


